src/app.py
from flask  import Flask
from flask import render_template

from src.common.database import Database

app = Flask(__name__)
app.config.from_object('config')
app.secret_key = "123"



@app.before_first_request
def init_db():
    Database.initialize()

@app.route('/')
def home():
    return render_template('home.jinja2')

from src.models.users.views import user_blueprint
from src.models.alerts.views import alert_blueprint
from src.models.stores.views import store_blueprint
app.register_blueprint(user_blueprint, url_prefix="/users")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")
app.register_blueprint(store_blueprint, url_prefix="/stores")

src/models/alerts/views.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask import session

from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decorators

alert_blueprint = Blueprint('alerts', __name__)

@alert_blueprint.route('/')
def index():
    return "This is the alerts index"

@alert_blueprint.route('/new', methods=['GET','POST'])
@user_decorators.requires_login     # redirect the user to 'users.login' if session['email'] is None
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()

    return render_template('alerts/create_alert.jinja2')


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET','POST'])
@user_decorators.requires_login     # redirect the user to 'users.login' if session['email'] is None
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)
    if request.method == 'POST':

        price_limit = float(request.form['price_limit'])

        alert = Alert.find_by_id(alert_id)
        alert.price_limit = price_limit
        alert.save_to_mongo()

        return redirect(url_for('users.user_alerts'))
    return render_template('alerts/edit_alert.jinja2', alert=alert)

@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))



@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))

@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template('alerts/alert.jinja2', alert = alert)


@alert_blueprint.route('/check_price/<string:alert_id>')
@user_decorators.requires_login
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id = alert_id ))

src/models/items/views.py
from flask  import Blueprint

item_blueprint = Blueprint('items', __name__)

@item_blueprint.route('/item/<string:name>')
def item_page(name):
    pass

src/models/stores/views.py
from flask import Blueprint
from flask import json
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for

from src.models.stores.store import Store
import src.models.users.decorators as user_decorators

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template("stores/store_index.jinja2", stores = stores)


@store_blueprint.route('/store/<string:store_id>')
def store_page(store_id):
    return render_template("stores/store.jinja2", store=Store.get_by_id(store_id))


@store_blueprint.route('/create', methods=['GET', 'POST'])
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('stores/create_store.jinja2')

@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@user_decorators.requires_admin_permission
def edit_store(store_id):
    store = Store.get_by_id(store_id)

    if request.method == 'POST':
        name = request.form['name']

        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])


        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('stores/edit_store.jinja2', store=store)

@store_blueprint.route('/delete/<string:store_id>')
@user_decorators.requires_admin_permission
def delete_store(store_id):
    Store.get_by_id(store_id).delete()
    return redirect(url_for('.index'))

src/models/users/views.py
from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask import session

from src.models.alerts.alert import Alert
from src.models.users.user import User
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators

user_blueprint = Blueprint('users', __name__)

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for("users.user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.jinja2")  # Send user a error if their login was invalid




@user_blueprint.route('/register', methods=['GET','POST'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.jinja2")


@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    print str(session['email'])
    alerts = user.get_alerts()
    print str(alert.json() for alert in alerts)
    return render_template('users/alerts.jinja2', alerts=alerts)

@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect( url_for('home') )


@user_blueprint.route('/check_alerts/<string:user_id>')
def check_for_alert(user_id):
    pass

src/templates/alerts/alert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/alerts/alert.jinja2
{% extends "base.html" %}

{% block content %}
    <div class="page-header">
        <h1>Alert:
            <small>for {{ alert.item.name }}</small>
        </h1>


    </div>
    <p>Last price found <strong>{{ alert.item.price }}</strong></p>
    <p>Last checked on <strong>{{ alert.last_checked.strftime('%d -%m-%y at %H: %M') }}</strong></p>

    <div class="panel panel-default">
        <div class="panel-body">
            <a class="btn btn-default" href="{{  alert.item.url }}" role="button" >visit site</a>
            <a class="btn btn-warning" href="{{ url_for('alerts.edit_alert', alert_id = alert._id) }}" role="button" >Edit alert</a>
            {%  if alert.active %}
            <a class="btn btn-danger" href="{{  url_for('alerts.deactivate_alert', alert_id=alert._id) }}" role="button" >Deactivate</a>
            {% else %}
            <a class="btn btn-success" href="{{  url_for('alerts.activate_alert', alert_id=alert._id) }}" role="button" >Activate</a>
            <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}" role="button" >Delete Alert</a>
            {% endif %}
            <a class="btn btn-warning" href="{{  url_for('alerts.check_alert_price', alert_id=alert._id) }}" role="button" >check alert</a>
        </div>

    </div>
    <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading"> Alert for {{ alert.item.name }}</h4>
        <p class="list-group-item-text"> Last price found at <strong>${{ alert.item.price }}</strong></p>
        <p class="list-group-item-text"> You have set item price below {{ alert.price_limit }}</p>
        <p class="list-group-item-text"> Item has been check
            on {{ alert.last_checked.strftime("%d-%m-%y. at %H:%M") }}</p>
    </a>
{% endblock %}

src/templates/alerts/create_alert.jinja2
{% extends "base.html" %}

{% block content %}
    <div class="page-header">
        <h1>Creating alert</h1>
    </div>
    <div class="form-size">
        <form action="{{ url_for('alerts.create_alert') }}" method="POST">
            <div class="form-group">
                <label for="name">Alert/Item name</label>
                <input type="text" id="name" class="form-control" name="name" placeholder="item name"/>
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" id="url" class="form-control" name="url" placeholder="Paste URL here"/>
            </div>
            <div class="form-group">
                <label for="price_limit">Price limit</label>
                <input type="text" id="url" class="form-control" name="price_limit" placeholder="input price limit"
                       aria-describedby="priceLimitBlock"/>
                <p id="priceLimitBlock" class="help-block">We will sent you email when price under this set price</p>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>


        </form>
    </div>

{% endblock %}

src/templates/alerts/edit_alert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/alerts/edit_alert.jinja2
{% extends "base.html" %}

{% block content %}
 <div class="page-header">
        <h1>edit alert</h1>
    </div>
    <div class="form-size">
        <form action="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" method="POST">
            <div class="form-group">
                <label for="name">Alert/Item name</label>
                <input type="text" id="name" class="form-control disabled" name="name" placeholder="item name" disabled/>
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" id="url" class="form-control disabled" name="url" placeholder="Paste URL here" disabled/>
            </div>
            <p>current price limit is {{ alert.price_limit }}</p>
            <div class="form-group">
                <label for="price_limit">Price limit</label>
                <input type="text" id="url" class="form-control" name="price_limit" placeholder="input price limit"
                       value="{{ alert.price_limit}}" aria-describedby="priceLimitBlock"/>
                <p id="priceLimitBlock" class="help-block">We will sent you email when price under this set price</p>
            </div>
            <button type="submit" class="btn btn-default">Update</button>


        </form>
    </div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pricing Services</title>

    {% include 'html_dependencies.jinja2' %}


</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" title="home">Pricing</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('stores.index') }}">Stores</a></li>
                <li><a href="{{ url_for('alerts.index') }}">Alerts</a></li>
            </ul>
            {% if session['email'] %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.user_alerts') }}"><span class="glyphicon glyphicon-alert"></span> Your Alerts</a></li>
                    <li><a href="{{ url_for('users.logout_user') }}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.register_user') }}"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
                    <li><a href="{{ url_for('users.login_user') }}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>
<div class="content container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% block content %}

<p>Hello world</p>

{% endblock %}

src/templates/home.jinja2
{% extends "base.html" %}

{% block content %}

    <div class="jumbotron">
        <h1>Priceing Srevice</h1>
        <p>we scan online store websites to alert you of price drops in items that interest you</p>
        <p>Just signup, and get started by adding the URL of an item that you wish to track.</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign up</a></p>
    </div>

{% endblock %}

src/templates/html_dependencies.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" ></script>

<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

src/templates/html_dependencies.jinja2
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"> </script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" ></script>

<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

src/templates/stores/create_store.jinja2
{% extends "base.html" %}

{% block content %}
    <div class="page-header">
        <h1>Create Store</h1>
    </div>
    <div class="form-size">
        <form  method="post">
            <div class="form-group">
                <label for="name">Store name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Store name">

            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix"
                       placeholder="Store prefix that you are going to buy the item"
                       aria-describedby="storeURLprefix">
                <span id="storeURLPrefixHelp"
                      class="help-block">What characters do URL of all items in this online store start with</span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name"
                       placeholder="span" value="span"
                       aria-describedby="tagName">
                <span id="tagName"
                      class="help-block">HTML tag name within item price</span>
            </div>
            <div class="form-group">
                <label for="query">Query</label>
                <input type="text" class="form-control" id="query" name="query"
                       placeholder='{"id":"price-now"}' value='{"id":"price-now"}'
                       aria-describedby="queryHelpBlock">
                <span id="queryHelpBlock"
                      class="help-block">whta json would have to do to find price</span>
            </div>
            <button type="submit" class="btn btn-default">Add store</button>
        </form>
    </div>

{% endblock %}

src/templates/stores/edit_store.jinja2
{% extends "base.html" %}

{% block content %}

<div class="page-header">
        <h1>Edit store</h1>
    </div>
    <div class="form-size">
        <form  method="post">
            <div class="form-group">
                <label for="name">Store name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Store name" value="{{ store.name }}">

            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix"
                       placeholder="Store prefix that you are going to buy the item"
                       aria-describedby="storeURLPrefix" value="{{ store.url_prefix }}">
                <span id="storeURLPrefixHelp"
                      class="help-block">What characters do URL of all items in this online store start with</span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name"
                       placeholder="span" value="{{ store.tag_name }}"
                       aria-describedby="tagName">
                <span id="tagName"
                      class="help-block">HTML tag name within item price</span>
            </div>
            <div class="form-group">
                <label for="query">Query</label>
                <input type="text" class="form-control" id="query" name="query"
                       placeholder='{"id":"price-now"}' value='{{ store.query | tojson }}'
                       aria-describedby="queryHelpBlock">
                <span id="queryHelpBlock"
                      class="help-block">whta json would have to do to find price</span>
            </div>
            <button type="submit" class="btn btn-warning">Update</button>
        </form>
    </div>

{% endblock %}

src/templates/stores/store.jinja2
{% extends "base.html" %}

{% block content %}

    <div class="page-header">
        <h1>Store
            <small>{{ store.name }}</small>
        </h1>

    </div>
    <p>All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p>

    {% if session['email'] in config.ADMINS %}
    <div class="panel panel-default">
        <div class="panel-body">
            <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id) }}" role="button">Edit
                Store</a>
            <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">Delete
                Store</a>
        </div>
    </div>
    {%  endif %}
{% endblock %}

src/templates/stores/store_index.jinja2
{% extends "base.html" %}

{% block content %}
    <div class="page-header">
        <h1>Stores
            <small>list of support stores</small>
        </h1>

    </div>
    <div class="list-group">
        {% for store in stores %}
            <a href="{{ url_for('stores.store_page', store_id=store._id) }}" class="list-group-item">
                <h4 class="list-group-item-title">{{ store.name }}</h4>
                <p class="list-group-item-text">All URLs in this stores list should start with
                    <strong> {{ store.url_prefix }}</strong></p></a>

        {% endfor %}
    </div>

    {% if session['email'] in config.ADMINS %}
        <a class="btn btn-success" href="{{ url_for('stores.create_store') }}">
            <span class="glyphicon glyphicon-plus"></span>Create new store</a>

    {% endif %}
{% endblock %}

src/templates/stores/store_list.jinja2
{% extends "base.html" %}

{% block content %}


        <h1>Under developing</h1>


{% endblock %}

src/templates/users/alerts.jinja2
{% extends "base.html" %}

{% block content %}
    <div class="page-header">
        <h1>Alerts
            <small> showing all existing in alerts</small>
        </h1>
    </div>
    <div class="list-group">
        {% for alert in alerts %}
            <a href="{{ url_for('alerts.get_alert_page', alert_id=alert._id) }}" class="list-group-item {{ 'list-group-item-warning' if not alert.active else '' }}">
                <h4 class="list-group-item-heading">
                    {{ '<span class="glyphicon glyphicon-remove-circle"></span>' if not alert.active else '' }}Alert for {{ alert.item.name }}</h4>
                <p class="list-group-item-text"> Last price found at <strong>${{ alert.item.price }}</strong></p>
                <p class="list-group-item-text"> You have set item price below {{ alert.price_limit }}</p>
            <p class="list-group-item-text"> Item has been check on {{ alert.last_checked.strftime("%d-%m-%y. at %H:%M") }}</p>
            </a>
        {% endfor %}

    </div>
    <a class="btn btn-success" href="{{ url_for('alerts.create_alert') }} "> <span class="glyphicon glyphicon-plus"></span> Create Alert</a>


{% endblock %}

src/templates/users/login.jinja2
{% extends "base.html" %}

{% block content %}
    <div class="form-size">
        <form action="{{ url_for('users.login_user') }}", method="POST">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" id="email" class="form-control" name="email" placeholder="Email"/>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" class="form-control" placeholder="password"/>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>

{% endblock %}

src/templates/users/register.jinja2
{% extends "base.html" %}

{% block content %}

    <div class="form-size">
        <form action="{{ url_for('users.register_user') }}" , method="POST">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" id="email" class="form-control" name="email" placeholder="Email"/>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" class="form-control" placeholder="password"/>
            </div>
            <button type="submit" class="btn btn-default">Sign up</button>
        </form>
    </div>


{% endblock %}